FROM quay.io/jupyter/base-notebook

RUN pip3 install torch==2.5.0 torchvision==0.20.0
RUN pip3 install numpy==2.1.2 Pillow==11.0.0 pandas==2.2.3 pyyaml==6.0.2
RUN pip3 install matplotlib==3.9.2 seaborn==0.13.2
RUN pip3 install diffusers==0.31.0 transformers==4.45.2
RUN pip3 install tqdm==4.66.5 shapely==2.0.6 wandb==0.18.5
RUN pip3 install scikit-learn==1.5.2